package com.varabyte.kobweb.site.model.listing

// DO NOT EDIT THIS FILE BY HAND! IT GETS AUTO-GENERATED BY `./gradlew generateSiteListing`
// Instead, edit the SITE_LISTING constant in `build.gradle.kts` and re-run the task.

val SITE_LISTING = buildList {
   add(
      Category(
         "guides",
         "Guides",
         Subcategory(
            "First Steps",
            Article("gettingstarted", "Getting Started"),
            Article("gettingkobweb", "Getting Kobweb"),
         ),
      )
   )
   add(
      Category(
         "widgets",
         "Widgets",
         Subcategory(
            "Forms",
            Article("button", "Button"),
         ),
         Subcategory(
            "Overlay",
            Article("tooltip", "Tooltip"),
         ),
      )
   )
   add(
      Category(
         "tutorials",
         "Tutorials",
         Subcategory(
            "",
            Article("createfirstsite", "Creating Your First Site"),
         ),
      )
   )
}

fun List<Category>.findArticle(categorySlug: String, articleSlug: String): Article? {
   return this.asSequence()
      .filter { it.slug == categorySlug }
      .flatMap { it.subcategories.asSequence() }
      .flatMap { it.articles.asSequence() }
      .firstOrNull { it.slug == articleSlug }
}
